# Generated by Django 6.0.4 on 2026-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickup_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
